### ISSUE TITLE
Ubuntu 20.04 on Macbookpro, bluetooth unstable

### ISSUE THREAD

**Issue by jayachandranm** [leifliddy/macbook12-bluetooth-driver#7]
I installed Ubuntu 20.04 on my MacbookPro 14,1 model. After the install Bluetooth didn't work. So I followed the instructions here and installed the driver. Now I was able to discover devices and pair my Logitech bluetooth mouse. I could use the mouse as normal. But soon I noticed few issues.
- The mouse will just stop working after some time. If I go to bluetooth settings again and try to connect, the system sometimes hang or my WiFi disconnects.
- Sometimes the mouse will not connect on a restart. But if I restart again it will start to work again.

Is there anything I can do to fix these issues? Also, if I want to switch back to original driver, what will be the clean way to remove this driver and switch back?

Thanks much for this great work!

**Comment by jayachandranm** [comment]
Here some errors from dmesg,


> [    3.582064] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4350c2-pcie for chip BCM4350/5
> 
> [    3.882493] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4350c2-pcie for chip BCM4350/5
> [    3.882515] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
> [    3.883188] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4350/5 wl0: Nov 26 2015 03:48:57 version 7.35.180.133 (r602372) FWID 01-c45b39d6
> 
> --------------
> 
> [    4.288907] Bluetooth: hci0: BCM: failed to write update baudrate (-16)
> [    4.288910] Bluetooth: hci0: Failed to set baudrate
> 
> -------------------
> 
> [    6.928852] Bluetooth: hci0: unknown advertising packet type: 0x20
> [    7.386609] Bluetooth: hci0: unknown advertising packet type: 0x10
> [    9.233392] rfkill: input handler disabled
> [   12.412048] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
> [   14.844225] Bluetooth: hci0: unknown advertising packet type: 0x23
> [   15.132601] rfkill: input handler enabled
> [   15.373730] Bluetooth: hci0: unknown advertising packet type: 0x20
> [   15.849607] Bluetooth: RFCOMM TTY layer initialized
> [   15.849612] Bluetooth: RFCOMM socket layer initialized
> [   15.849616] Bluetooth: RFCOMM ver 1.11
> [   17.000523] Bluetooth: hci0: unknown advertising packet type: 0x20
> [   19.207370] rfkill: input handler disabled
> [   19.626378] Bluetooth: hci0: unknown advertising packet type: 0x90
> [   19.824335] Bluetooth: hci0: unknown advertising packet type: 0x10
> [   21.976624] Bluetooth: hci0: unknown advertising packet type: 0x11
> [   30.856398] Bluetooth: hci0: unknown advertising packet type: 0x20
> [   31.788844] Bluetooth: hci0: unknown advertising packet type: 0x20
> [   32.134729] Bluetooth: hci0: unknown advertising packet type: 0x20
> [   40.702291] Bluetooth: hci0: unknown advertising packet type: 0x10
> [   44.198529] Bluetooth: hci0: unknown advertising packet type: 0x20
> 

--

**Comment by johnjeffers** [comment]
+1, would also appreciate some uninstall instructions, please

**Comment by jayachandranm** [comment]
@johnjeffers I looked a bit more detail into the scripts and discussions. Looks to me that the driver is not really changed, but the script here just patches the current kernel driver (hci_uart) with some updates. And the update goes to the current kernel versions driver update folder. I still have issues with the bluetooth driver, so would like to hear from the maintainers.

**Comment by leifliddy** [comment]
Unfortunately, with these macbooks the normal method of nullifing the autosuspend_delay_ms value won't work

cat: '/sys/devices/virtual/misc/uhid/0005:1532:0056.0002/input/input13/power/autosuspend_delay_ms': Input/output error.

I just created that I've mapped to a keyboard shorcut to reconnect the mouse if it ever disconnects. But, I rarely have to use this anymore since the mouse seems to connect for quite a long time. 
Although, I don't use the macbook for for in 20 min at a time normally so YMMV. 


if the mouse disconnects, try running this script (as a normal user)
```
#!/bin/bash

orochi_mac='C5:77:C8:3F:E7:DB'   #obviously substitute the MAC address for your device

echo -e "connect $orochi_mac\n" | bluetoothctl
echo -e 'scan on\n' | bluetoothctl
echo -e 'discoverable on' | bluetoothctl
sleep 7
echo -e "connect $orochi_mac\n" | bluetoothctl
sleep 4
echo -e 'quit\n' | bluetoothctl
sleep 5
```

I've also used another method in the past (which I found in my notes), but I haven't used it in ages, and don't remember if it helped or to (need to run as root or with sudo)
```
#!/bin/bash
orochi_mac='C5:77:C8:3F:E7:DB' 	#subtitute your MAC here

orochi_handle="$(hcitool con | grep $orochi_mac | awk '{print $5}')"
[[ -n $orochi_handle ]] && sudo hcitool lecup --handle $orochi_handle --latency 0 --min 6 --max 8 
```, 
to switch back to the stock driver, just remove the module the install script created
```rm /usr/lib/modules/$(uname -r)/updates/hci_uart.ko```

**Comment by jayachandranm** [comment]
Thanks @leifliddy, really appreciate your support here. For my MacPro Bluetooth and sound are the remaining issues. If Bluetooth works the rest are less important for me. I will try the scripts to reconnect. As the current driver is not installed using dkms, it looks like we have to reinstall with each kernel update. I updated my kernel and now the built-in bluetooh is not working again. I will install the update again and try. In the meantime, I tried a bluetooth dongle and it worked during my tests.

**Comment by leifliddy** [comment]
I'm not sure that you can install the driver with dkms since the ```hci_uart.ko``` module already exists in the stock kernel. I'll look into when I return from vacation.

**Comment by leifliddy** [comment]
Due to the nature of this module and how it's patched + compiled -- it's just not a viable option to implement a dkms feature. Basically, all the ```install.bluetooth.sh``` script is doing is removing a few lines from ```hci_bcm.c``` and then compiling and installing the resulting ```hci_uart.ko``` module.

I understand it might be a pain for some people to have to manually run a script every time they update their kernel, but I don't see anyway around that. With that said, I'll keep in open mind, if someone can present me with a dkms implementation that works and doesn't require constant maintenance/upkeep -- then I would be onboard with that for sure.
